---
- name: Exercise 1b
  hosts: arista:cisco:juniper
  gather_facts: False
  tasks:
    - name: Gather show ip arp output (eos)
      eos_command:
        commands: show ip arp
      register: show_ip_arp_eos
      when: ansible_network_os == "eos"
      tags: eos

    - name: Gather show ip arp output (ios)
      ios_command:
        commands: show ip arp
      register: show_ip_arp_ios
      when: ansible_network_os == "ios"
      tags: ios

    - name: Print ARP output
      debug:
        var: show_ip_arp_eos
      when: ansible_network_os == "eos"
      tags: eos
