---

- name: Textfsm and combine
  hosts: cisco
  gather_facts: False
  vars:
    fsm_template: "cisco_ios_show_ip_interface_brief.template"

  tasks:
    - name: Executing command
      ios_command:
        commands: show ip int brief
      register: output

    - name: Processing with textfsm
      set_fact:
        show_ip: "{{ output.stdout[0] | parse_cli_textfsm(fsm_template) }}"

    - name: Create a dictionary with intf_name as the key
      set_fact:
        ip_dict: "{{ ip_dict | default({}) | combine({item['INTF']: item['IPADDR']}) }}"
      loop: "{{ show_ip }}"

    - debug:
        var: ip_dict
