---
- name: Print out variables
  hosts: cisco3
  gather_facts: False
  vars: #play level
    dns1: 8.8.8.8
    dns2: 8.8.4.4
  vars_files:
    - my_vars.yml
  tasks:
    - name: Debuggiing...
      debug:
        msg: "{{ ip_addr1 }}"
    - name: Var from inventory
      debug:
        msg: "{{ ansible_host }}"
    - name: Var from inventory
      debug:
        msg: "{{ inventory_hostname }}"
