- name: Interface configuration
  hosts: cisco1
  gather_facts: False
  tasks:
    - name: Update interface config
      ios_interfaces:
        config:
          - name: GigabitEthernet0/1
            description: 'Testing Ansible configuration'
            enabled: True
            # speed: "100"
            # duplex: full
            speed: auto
            duplex: auto
        state: merged
        # state: replaced

