---
- name: Test Jinja2
  hosts: cisco1
  gather_facts: False
  vars:
    cisco_interfaces:
      - GigabitEthernet0/0
      - GigabitEthernet0/1
      - GigabitEthernet0/2
      - GigabitEthernet0/3
  tasks:
    - template:
        src: int_config.j2
        dest: "./CFGS/{{ inventory_hostname }}-interfaces.txt"
