---
- name: VLAN configuration
  hosts: arista1
  gather_facts: False
  tasks:
    - name: Merge provided configuration with device configuration
      eos_vlans:
        config:
          - name: Blue10
            vlan_id: 10
            state: active
          - name: Blue20
            vlan_id: 20
            state: active
          - name: Blue30
            vlan_id: 30
            state: active
        state: merged
#        state: replaced
