---
- name: With Testing
  hosts: local
  tasks:
    - name: Test with_items
      debug:
        msg: Hello world
      with_items:
        - 10.10.10.1
        - 10.10.20.1
        - 10.10.30.1
        - 10.10.40.1
        - 10.10.50.1

    - name: Test loop
      debug:
        msg: Hello world (loop)
      loop:
        - 10.10.10.1
        - 10.10.20.1
        - 10.10.30.1
        - 10.10.40.1
        - 10.10.50.1
