---
- name: TextFSM Example3
  hosts: cisco5
  gather_facts: True
  vars:
    platform: "cisco_ios"
    command: "show ip int brief"
    textfsm_rel_path: "ntc-templates/templates/"

  tasks:
    - name: Executing command
      ios_command:
        commands: "{{ command }}"
      register: output

    - debug:
        var: output

    # This is only needed so our automated tests work properly
    - name: "Set home directory as ntc_parse doesn't understand ~"
      set_fact:
        textfsm_index: "{{ inventory_dir }}/{{textfsm_rel_path }}"

    - set_fact:
       show_ip: "{{ output.stdout[0] | ntc_parse(command, platform, textfsm_index ) }}"

    - debug:
        var: show_ip
