---
- name: IOS Example
  hosts: cisco2:cisco3
  gather_facts: True
  vars:
    - domain_name : vodafone.com
    - ntp_server1: 130.126.24.24
    - ntp_server2: 152.2.21.1
    - dns_server1: 8.8.8.8
    - dns_server2: 8.8.4.4
  tasks:
    - name: Global config
      ios_config:
        src: "/home/cokbilir/ios_config.j2"
        diff_against: running
