---
- name: IOS Example1
  hosts: cisco1
  gather_facts: False
  tasks:
    - name: Global config
      ios_config:
        lines:
          - ip domain name vodafone.com
          - ntp server 130.126.24.24
          - ntp server 152.2.21.1
