---
- name: Pipe JSON
  hosts: arista1
  gather_facts: False
  tasks:
    - name: Executing command
      eos_command:
        commands: show version | json
      register: output

    - set_fact:
        show_ver: "{{ output['stdout'][0] }}"

    - debug:
        msg: "{{ show_ver }}"
        #msg: "OS Version: {{ show_ver.version }}"
