---
- name: When Testing
  hosts: local
  gather_facts: False
  vars:
    my_str: whatever

  tasks:
    - name: Testing string equality
      debug:
        msg: whatever
      when: my_str == 'whatever'
