---
- name: IOS Example
  hosts: cisco
  gather_facts: True
  tasks:
    - debug:
        var: hostvars

    - debug:
        msg: "{{ hostvars['cisco1'] }}"

    - debug:
        msg: 
          - "Cisco1: {{ hostvars['cisco1']['bgp_router_id'] }}"
          - "Cisco2: {{ hostvars['cisco2']['bgp_router_id'] }}"
          - "Cisco3: {{ hostvars['cisco3']['bgp_router_id'] }}"
          - "Cisco4: {{ hostvars['cisco4']['bgp_router_id'] }}"

